language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1" #PyPy2.7
  - "pypy3" # Pypy3 2.4.0
  
matrix:
  allow_failures:
#    - python: "2.6"
    - python: "3.2"
    - python: "3.7-dev"
    - python: "nightly"

install:
  #pip install -r requirements.txt
  pip install codecov

script:
  python setup.py test
  
after_success:
  codecov
